### ISSUE TITLE
5001 but how to connect?

### ISSUE THREAD

**Issue by Boca-NeedM** [luadch/certmanager#1]
Should users connect with: adcs://86.107.xx.xxx:5001
Or with:
adcs://86.107.xx.xxx:5001/?kp=SHA256/DSH43UD2JGXKV4FPMLWTNXOC4KVR5ABLYHDF6NTQBP ect ..

What is the differents?

**Comment by pulsar-de** [comment]
First of all: The certmanager can't connect to any hub, maybe you mean the announcer client or just your normal client.

The difference between:  `adcs:\\<ip>:<port>`  and  `adcs:\\<ip>:<port>/?kp=SHA256/<keyprint>`

The keyprint is the checksum of the hub certificate. when you use it, your client checks whether the keyprint matches the hub certificate. if everything is ok you will see an [S] in the hub tab, otherwise a [U] is displayed.
